services:
  ldap:
    build:
      context: ./ldap
    hostname: ldap
    environment:
      - CONTAINER_LOG_LEVEL=debug
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_TLS_VERIFY_CLIENT=never
    networks:
      - compute

  base:
    build:
      context: ./base
    image: hpcts-local-base:latest
    networks:
      - compute
    depends_on:
      - ldap

  htcondor:
    hostname: htc.mini
    build:
      context: ./htcondor
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - home:/home
    expose:
      - "22"
    ports:
      - "127.0.0.1:7222:22"
    depends_on:
      - base

  ondemand:
    build:
      context: ./ondemand
      args:
        HPCTS_VERSION: $HPCTS_VERSION
    command: ["serve"]
    hostname: ondemand
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - home:/home
    expose:
      - "22"
    ports:
      - "127.0.0.1:3443:3443"
      - "127.0.0.1:5554:5554"
    depends_on:
      - htcondor

volumes:
  etc_munge:
  home:

networks:
  compute:
