#!/bin/bash

#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <hostname>" >&2
    exit 1
fi

HOST=${1}

if [[ ! "$HOST" =~ ^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*$ ]]; then
    echo "Error: '$HOST' is not a valid hostname" >&2
    exit 1
fi

./tunnel "3443" "${HOST}"
./tunnel "5554" "${HOST}"
